import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypeScript from 'eslint-config-next/typescript'

const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'build/**',
      'dist/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      // Browser binaries pinned to this volume — ~850 MB of vendor JS that is
      // not ours to lint.
      '.playwright-browsers/**',
      // Generated by Payload — not hand-maintained.
      'src/payload-types.ts',
      'src/app/(payload)/admin/importMap.js',
    ],
  },

  ...nextCoreWebVitals,
  ...nextTypeScript,

  {
    rules: {
      /*
       * PRD Master §53 and CLAUDE.md §84: `any` is not how we make TypeScript
       * quiet. An error, not a warning, so it cannot accumulate.
       */
      '@typescript-eslint/no-explicit-any': 'error',

      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],

      /*
       * PRD Nº4 §82 requires structured logging without secrets. Stray
       * `console.log` is how credentials end up in container logs.
       */
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },

  {
    // Scripts and config files legitimately report to stdout.
    files: ['src/search/reindex.ts', 'src/payload/jobs/**/*.ts', '*.config.{ts,mjs,js}'],
    rules: {
      'no-console': 'off',
    },
  },

  {
    /*
     * Payload generates migration files, including imports it does not always
     * use. They stay linted for everything else — a migration is production
     * code and a real risk surface (see MASTER-IMPLEMENTATION-PLAN §7, R-04) —
     * but unused-symbol noise from the generator is not actionable.
     */
    files: ['src/payload/migrations/**/*.ts'],
    rules: {
      '@typescript-eslint/no-unused-vars': 'off',
    },
  },
]

export default config
