/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    authors: Author;
    categories: Category;
    topics: Topic;
    people: Person;
    organizations: Organization;
    media: Media;
    articles: Article;
    investigations: Investigation;
    opinions: Opinion;
    'data-stories': DataStory;
    'video-stories': VideoStory;
    sources: Source;
    'evidence-documents': EvidenceDocument;
    redirects: Redirect;
    corrections: Correction;
    'audit-events': AuditEvent;
    tips: Tip;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    investigations: InvestigationsSelect<false> | InvestigationsSelect<true>;
    opinions: OpinionsSelect<false> | OpinionsSelect<true>;
    'data-stories': DataStoriesSelect<false> | DataStoriesSelect<true>;
    'video-stories': VideoStoriesSelect<false> | VideoStoriesSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    'evidence-documents': EvidenceDocumentsSelect<false> | EvidenceDocumentsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    corrections: CorrectionsSelect<false> | CorrectionsSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    tips: TipsSelect<false> | TipsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    homepage: Homepage;
    'breaking-news': BreakingNew;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'breaking-news': BreakingNewsSelect<false> | BreakingNewsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      syncSearch: TaskSyncSearch;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Cuentas internas del sistema editorial. Cada persona debe tener su propia cuenta; nunca se comparten (PRD Nº4 §96).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Nombre de la persona tal como aparecerá en el panel.
   */
  name: string;
  /**
   * Determina qué puede hacer esta persona. Solo un administrador puede modificarlo.
   */
  role: 'admin' | 'editor' | 'author';
  /**
   * Deshabilitado impide el inicio de sesión. Al salir del equipo, deshabilitar de inmediato (PRD Nº4 §96).
   */
  status: 'active' | 'suspended' | 'disabled';
  /**
   * Área o mesa de trabajo. Informativo; no otorga permisos.
   */
  department?: string | null;
  /**
   * Indicador de estado. La implementación de MFA es posterior (ver gap G-20); este campo no activa nada por sí solo.
   */
  mfaEnabled?: boolean | null;
  /**
   * Lo escribe el sistema al iniciar sesión.
   */
  lastLoginAt?: string | null;
  /**
   * Lo escribe el sistema al cambiar la contraseña.
   */
  passwordChangedAt?: string | null;
  /**
   * Notas internas de administración. No registrar aquí secretos, contraseñas ni códigos de recuperación (PRD Nº5 §5).
   */
  securityNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Firmas públicas. Al retirar a alguien del equipo, desactivar — nunca borrar, o se pierden las firmas publicadas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * Como debe aparecer en la firma.
   */
  name: string;
  /**
   * Parte final de la URL. Se genera desde el título y se congela al publicar; cambiarlo después crea un redirect automático.
   */
  slug: string;
  /**
   * Se activa en la primera publicación. Protege una URL ya difundida.
   */
  slugLocked?: boolean | null;
  /**
   * Ejemplo: «Periodista de investigación». Aparece bajo la firma.
   */
  jobTitle?: string | null;
  /**
   * Una o dos líneas, para la ficha al pie del artículo.
   */
  shortBio?: string | null;
  /**
   * Para la página de autor. PRD SEO §32 pide trayectoria real, no un párrafo vago.
   */
  bio?: string | null;
  expertise?:
    | {
        area: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional y público. No usar el correo interno de la cuenta del CMS.
   */
  emailPublic?: string | null;
  /**
   * Solo perfiles oficiales verificables: PRD SEO §33 los emite como `sameAs` en structured data.
   */
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Desactivar al salir del equipo. Las firmas publicadas se conservan.
   */
  active?: boolean | null;
  /**
   * Fondo neutro y encuadre consistente (PRD Nº10 §101). Aparece en la firma y en la página de autor.
   */
  portrait?: (number | null) | Media;
  /**
   * Todo es opcional. Si se deja vacío, el sistema deriva los valores del titular, la bajada y la imagen principal.
   */
  seo?: {
    /**
     * Solo si el titular editorial no funciona bien en resultados de búsqueda. No debe cambiar el significado (PRD SEO §27).
     */
    metaTitle?: string | null;
    /**
     * Debe describir, no ser clickbait. Si se deja vacío, se usa la bajada.
     */
    metaDescription?: string | null;
    /**
     * Solo para casos excepcionales. Nunca incluir parámetros de campaña como utm_source (PRD SEO §9).
     */
    canonical?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Excluye esta pieza de los buscadores. Usar con criterio: una nota publicada normalmente debe indexarse.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Imágenes editoriales públicas. La evidencia NO va aquí — tiene su propio almacenamiento con control de acceso.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * SHA-256 de los bytes originales. Sirve para detectar duplicados.
   */
  checksum?: string | null;
  /**
   * Describe lo relevante de la imagen. No escribir «foto», «imagen» ni el nombre del medio (PRD Nº10 §6).
   */
  alt?: string | null;
  /**
   * Solo para imágenes sin contenido informativo. El frontend emite alt="" (PRD Nº10 §8).
   */
  decorative?: boolean | null;
  /**
   * Aporta contexto. No repetir el texto alternativo (PRD Nº10 §9).
   */
  caption?: string | null;
  /**
   * Ejemplo: «Foto: Juan Pérez / Clasificados Colombia» o «Cortesía: Fiscalía».
   */
  credit?: string | null;
  photographer?: string | null;
  /**
   * De dónde proviene: propio, agencia, cortesía, entidad pública.
   */
  source?: string | null;
  mediaType?:
    | ('photo' | 'illustration' | 'graphic' | 'logo' | 'screenshot' | 'document_preview' | 'video_poster' | 'other')
    | null;
  /**
   * PRD Nº10 §119: una imagen con licencia desconocida no debe publicarse. No asumir que algo disponible en internet se puede usar.
   */
  license?:
    ('owned' | 'licensed' | 'creative_commons' | 'public_domain' | 'courtesy' | 'editorial_use' | 'unknown') | null;
  /**
   * No confundir con el fotógrafo (PRD Nº10 §15).
   */
  copyrightHolder?: string | null;
  /**
   * Para licencias con duración limitada. Genera alerta al acercarse.
   */
  rightsExpiration?: string | null;
  /**
   * PRD Nº10 §43: nunca presentar una imagen generada como fotografía documental real.
   */
  syntheticMedia?: ('none' | 'ai_generated' | 'ai_modified' | 'composite' | 'illustration') | null;
  /**
   * Restricciones internas. Nunca se envían al frontend público (PRD Nº10 §16, §47).
   */
  usageNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    article?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    portrait?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Secciones editoriales. Retirar con «Activa = falso», no borrando.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Parte final de la URL. Se genera desde el título y se congela al publicar; cambiarlo después crea un redirect automático.
   */
  slug: string;
  /**
   * Se activa en la primera publicación. Protege una URL ya difundida.
   */
  slugLocked?: boolean | null;
  /**
   * Se muestra en la página de sección. PRD SEO §57 pide páginas editoriales reales, no listados.
   */
  description?: string | null;
  /**
   * Vacío para una sección principal. Una sola profundidad.
   */
  parent?: (number | null) | Category;
  /**
   * Si se deja vacío se usa el nombre. Útil cuando el nombre es largo.
   */
  navigationLabel?: string | null;
  /**
   * Define el orden en la navegación. Menor aparece primero.
   */
  order?: number | null;
  /**
   * Al desactivar, deja de ser visible públicamente sin romper lo publicado.
   */
  active?: boolean | null;
  /**
   * Todo es opcional. Si se deja vacío, el sistema deriva los valores del titular, la bajada y la imagen principal.
   */
  seo?: {
    /**
     * Solo si el titular editorial no funciona bien en resultados de búsqueda. No debe cambiar el significado (PRD SEO §27).
     */
    metaTitle?: string | null;
    /**
     * Debe describir, no ser clickbait. Si se deja vacío, se usa la bajada.
     */
    metaDescription?: string | null;
    /**
     * Solo para casos excepcionales. Nunca incluir parámetros de campaña como utm_source (PRD SEO §9).
     */
    canonical?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Excluye esta pieza de los buscadores. Usar con criterio: una nota publicada normalmente debe indexarse.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Temas transversales. Alimentan las páginas de tema (/tema/[slug]).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number;
  name: string;
  /**
   * Parte final de la URL. Se genera desde el título y se congela al publicar; cambiarlo después crea un redirect automático.
   */
  slug: string;
  /**
   * Se activa en la primera publicación. Protege una URL ya difundida.
   */
  slugLocked?: boolean | null;
  /**
   * Contexto del tema. Encabeza la página del hub.
   */
  description?: string | null;
  /**
   * Para navegación contextual. No incluir este mismo tema.
   */
  relatedTopics?: (number | Topic)[] | null;
  /**
   * Encabeza la página del tema.
   */
  image?: (number | null) | Media;
  active?: boolean | null;
  /**
   * Todo es opcional. Si se deja vacío, el sistema deriva los valores del titular, la bajada y la imagen principal.
   */
  seo?: {
    /**
     * Solo si el titular editorial no funciona bien en resultados de búsqueda. No debe cambiar el significado (PRD SEO §27).
     */
    metaTitle?: string | null;
    /**
     * Debe describir, no ser clickbait. Si se deja vacío, se usa la bajada.
     */
    metaDescription?: string | null;
    /**
     * Solo para casos excepcionales. Nunca incluir parámetros de campaña como utm_source (PRD SEO §9).
     */
    canonical?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Excluye esta pieza de los buscadores. Usar con criterio: una nota publicada normalmente debe indexarse.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Personas mencionadas editorialmente. Aparecer aquí no implica ninguna imputación: el contexto va en el texto periodístico.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  /**
   * Parte final de la URL. Se genera desde el título y se congela al publicar; cambiarlo después crea un redirect automático.
   */
  slug: string;
  /**
   * Se activa en la primera publicación. Protege una URL ya difundida.
   */
  slugLocked?: boolean | null;
  /**
   * Función pública o cargo verificable. Ejemplo: «Ministro de Transporte (2022-2024)».
   */
  roleDescription?: string | null;
  /**
   * Vínculos institucionales verificables, no asociaciones sugeridas.
   */
  organizations?: (number | Organization)[] | null;
  /**
   * Contexto factual y atribuible. No redactar conclusiones ni juicios: eso pertenece al artículo, con firma responsable.
   */
  description?: string | null;
  portrait?: (number | null) | Media;
  /**
   * De dónde sale la información de esta ficha. Solo fuentes públicas y verificables.
   */
  publicSources?:
    | {
        title: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Entidades mencionadas editorialmente.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  /**
   * Parte final de la URL. Se genera desde el título y se congela al publicar; cambiarlo después crea un redirect automático.
   */
  slug: string;
  /**
   * Se activa en la primera publicación. Protege una URL ya difundida.
   */
  slugLocked?: boolean | null;
  organizationType: 'government' | 'company' | 'ngo' | 'political' | 'international' | 'media' | 'other';
  logo?: (number | null) | Media;
  description?: string | null;
  website?: string | null;
  location?: string | null;
  publicSources?:
    | {
        title: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Noticias, análisis, perfiles y crónicas. Las investigaciones tienen su propia colección.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * El titular visible. PRD SEO §27 exige que coincida con el headline del structured data.
   */
  title: string;
  /**
   * Parte final de la URL. Se genera desde el título y se congela al publicar; cambiarlo después crea un redirect automático.
   */
  slug: string;
  /**
   * Se activa en la primera publicación. Protege una URL ya difundida.
   */
  slugLocked?: boolean | null;
  /**
   * Resume y aporta contexto. Se usa como meta description cuando no hay override.
   */
  dek?: string | null;
  /**
   * Qué clase de pieza es. Distinto de la sección.
   */
  contentType: 'news' | 'reportage' | 'analysis' | 'explainer' | 'interview' | 'profile' | 'chronicle';
  /**
   * Una sola sección principal (PRD Nº7 §28).
   */
  category: number | Category;
  topics?: (number | Topic)[] | null;
  /**
   * Toda pieza publicada lleva firma responsable (PRD SEO §31).
   */
  authors: (number | Author)[];
  /**
   * PRD SEO §44: debe representar la historia. No usar el logo ni una placa de texto si existe fotografía editorial.
   */
  hero?: {
    image?: (number | null) | Media;
    /**
     * Opcional. Si se deja vacío se usa el pie de la imagen.
     */
    captionOverride?: string | null;
  };
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Alimentan la navegación contextual. PRD SEO §55 prioriza la selección manual sobre lo automático.
   */
  relations?: {
    relatedArticles?: (number | Article)[] | null;
    /**
     * Relacionar a alguien aquí no implica imputación. El contexto va en el texto.
     */
    people?: (number | Person)[] | null;
    organizations?: (number | Organization)[] | null;
    /**
     * Base documental. Las fuentes internas no se muestran al público (ver visibilidad en Fuentes).
     */
    sources?: (number | Source)[] | null;
  };
  /**
   * Lo registra el sistema. Determina quién puede editar el borrador.
   */
  createdBy?: (number | null) | User;
  /**
   * Quién acompaña esta pieza. Da acceso de edición además del autor.
   */
  assignedEditor?: (number | null) | User;
  /**
   * Estado de la pieza dentro del proceso de redacción. La visibilidad pública se deriva de aquí, no se controla por separado.
   */
  workflow: {
    /**
     * Publicar exige rol autorizado, verificación completa y revisión legal resuelta.
     */
    editorialStatus:
      'draft' | 'editing' | 'fact_check' | 'legal_review' | 'approved' | 'scheduled' | 'published' | 'archived';
    factCheckStatus?: ('not_required' | 'not_started' | 'in_progress' | 'verified' | 'issues_found') | null;
    legalStatus?: ('not_required' | 'pending' | 'approved' | 'changes_required') | null;
    /**
     * Notas internas. Nunca se envían al frontend público (PRD Nº8 §170).
     */
    reviewNotes?: string | null;
  };
  publication?: {
    /**
     * Fecha visible al lector. Debe coincidir con el structured data.
     */
    publishedAt?: string | null;
    /**
     * Se registra una sola vez, en la primera publicación. No se modifica.
     */
    firstPublishedAt?: string | null;
    /**
     * Solo cuando el contenido cambia de forma sustantiva. No se toca por correcciones de forma (PRD SEO §29).
     */
    modifiedAt?: string | null;
    /**
     * Debe ser una fecha futura.
     */
    scheduledAt?: string | null;
  };
  /**
   * Todo es opcional. Si se deja vacío, el sistema deriva los valores del titular, la bajada y la imagen principal.
   */
  seo?: {
    /**
     * Solo si el titular editorial no funciona bien en resultados de búsqueda. No debe cambiar el significado (PRD SEO §27).
     */
    metaTitle?: string | null;
    /**
     * Debe describir, no ser clickbait. Si se deja vacío, se usa la bajada.
     */
    metaDescription?: string | null;
    /**
     * Solo para casos excepcionales. Nunca incluir parámetros de campaña como utm_source (PRD SEO §9).
     */
    canonical?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Excluye esta pieza de los buscadores. Usar con criterio: una nota publicada normalmente debe indexarse.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Base documental de las piezas. NUNCA registrar aquí la identidad de una fuente confidencial.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  /**
   * Descripción de la fuente documental. No escribir nombres de fuentes reservadas.
   */
  title: string;
  sourceType:
    | 'official_document'
    | 'public_database'
    | 'interview'
    | 'press_release'
    | 'court_record'
    | 'law'
    | 'academic'
    | 'news'
    | 'other';
  /**
   * Interna por defecto. Solo las públicas se sirven al frontend y al índice de búsqueda.
   */
  visibility: 'public' | 'internal';
  /**
   * Quién produjo el documento. Ejemplo: «Contraloría General».
   */
  publisher?: string | null;
  url?: string | null;
  /**
   * Copia archivada. Las fuentes oficiales desaparecen de internet con frecuencia; sin esto, una investigación pierde su respaldo.
   */
  archiveUrl?: string | null;
  publishedAt?: string | null;
  /**
   * Cuándo se verificó. Importa cuando la fuente cambia o se cae.
   */
  accessedAt?: string | null;
  /**
   * Nunca se envían al frontend público. Tampoco escribir aquí identidades reservadas.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Investigaciones. No se publican sin verificación completa, revisión legal aprobada y metodología documentada.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investigations".
 */
export interface Investigation {
  id: number;
  title: string;
  /**
   * Parte final de la URL. Se genera desde el título y se congela al publicar; cambiarlo después crea un redirect automático.
   */
  slug: string;
  /**
   * Se activa en la primera publicación. Protege una URL ya difundida.
   */
  slugLocked?: boolean | null;
  dek?: string | null;
  hero?: {
    image?: (number | null) | Media;
    captionOverride?: string | null;
  };
  authors: (number | Author)[];
  /**
   * Quién editó la investigación, cuando corresponda acreditarlo.
   */
  editors?: (number | Author)[] | null;
  /**
   * Qué encontramos, en pocas líneas.
   */
  summary?: string | null;
  /**
   * Lo que la investigación demostró. Cada hallazgo debe poder rastrearse a una fuente.
   */
  keyFindings?:
    | {
        headline: string;
        description?: string | null;
        sources?: (number | Source)[] | null;
        importance?: ('primary' | 'normal' | 'context') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * PRD SEO §60: si un capítulo no es sustancial, usar anclas internas en vez de crear una URL delgada.
   */
  chapters?:
    | {
        title: string;
        /**
         * Parte final de la URL. Se genera desde el título y se congela al publicar; cambiarlo después crea un redirect automático.
         */
        slug: string;
        intro?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        sources?: (number | Source)[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Modelada como array y no como colección aparte (resolución del conflicto C-05). Si en algún momento hace falta reutilizar eventos entre investigaciones, se promueve a colección.
   */
  timeline?:
    | {
        date: string;
        title: string;
        description?: string | null;
        sources?: (number | Source)[] | null;
        id?: string | null;
      }[]
    | null;
  topics?: (number | Topic)[] | null;
  /**
   * ATENCIÓN: si esta lista no está vacía, la revisión legal debe estar APROBADA para publicar. Mencionar a alguien no implica imputación; el contexto va en el texto.
   */
  people?: (number | Person)[] | null;
  organizations?: (number | Organization)[] | null;
  sources?: (number | Source)[] | null;
  /**
   * Cómo se investigó: verificación de documentos, manejo de datos, entrevistas, solicitudes oficiales. Obligatoria para publicar.
   */
  methodology?: string | null;
  /**
   * PRD SEO §75: mostrar qué cambió. Una investigación viva se actualiza; el lector debe poder ver la historia del cambio.
   */
  updates?:
    | {
        date: string;
        summary: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lo registra el sistema. Determina quién puede editar el borrador.
   */
  createdBy?: (number | null) | User;
  /**
   * Quién acompaña esta pieza. Da acceso de edición además del autor.
   */
  assignedEditor?: (number | null) | User;
  /**
   * Estado de la pieza dentro del proceso de redacción. La visibilidad pública se deriva de aquí, no se controla por separado.
   */
  workflow: {
    /**
     * Publicar exige rol autorizado, verificación completa y revisión legal resuelta.
     */
    editorialStatus:
      'draft' | 'editing' | 'fact_check' | 'legal_review' | 'approved' | 'scheduled' | 'published' | 'archived';
    factCheckStatus?: ('not_required' | 'not_started' | 'in_progress' | 'verified' | 'issues_found') | null;
    legalStatus?: ('not_required' | 'pending' | 'approved' | 'changes_required') | null;
    /**
     * Notas internas. Nunca se envían al frontend público (PRD Nº8 §170).
     */
    reviewNotes?: string | null;
  };
  publication?: {
    /**
     * Fecha visible al lector. Debe coincidir con el structured data.
     */
    publishedAt?: string | null;
    /**
     * Se registra una sola vez, en la primera publicación. No se modifica.
     */
    firstPublishedAt?: string | null;
    /**
     * Solo cuando el contenido cambia de forma sustantiva. No se toca por correcciones de forma (PRD SEO §29).
     */
    modifiedAt?: string | null;
    /**
     * Debe ser una fecha futura.
     */
    scheduledAt?: string | null;
  };
  /**
   * Todo es opcional. Si se deja vacío, el sistema deriva los valores del titular, la bajada y la imagen principal.
   */
  seo?: {
    /**
     * Solo si el titular editorial no funciona bien en resultados de búsqueda. No debe cambiar el significado (PRD SEO §27).
     */
    metaTitle?: string | null;
    /**
     * Debe describir, no ser clickbait. Si se deja vacío, se usa la bajada.
     */
    metaDescription?: string | null;
    /**
     * Solo para casos excepcionales. Nunca incluir parámetros de campaña como utm_source (PRD SEO §9).
     */
    canonical?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Excluye esta pieza de los buscadores. Usar con criterio: una nota publicada normalmente debe indexarse.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Columnas y análisis de opinión. Siempre marcadas como opinión ante el lector.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opinions".
 */
export interface Opinion {
  id: number;
  title: string;
  /**
   * Parte final de la URL. Se genera desde el título y se congela al publicar; cambiarlo después crea un redirect automático.
   */
  slug: string;
  /**
   * Se activa en la primera publicación. Protege una URL ya difundida.
   */
  slugLocked?: boolean | null;
  dek?: string | null;
  /**
   * Fijo. Alimenta el frontend, el structured data y la búsqueda para que nunca se confunda con reportería.
   */
  contentNature: 'opinion';
  /**
   * Una sola firma: una opinión es de quien la escribe.
   */
  author: number | Author;
  hero?: {
    image?: (number | null) | Media;
    captionOverride?: string | null;
  };
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Lo registra el sistema. Determina quién puede editar el borrador.
   */
  createdBy?: (number | null) | User;
  /**
   * Quién acompaña esta pieza. Da acceso de edición además del autor.
   */
  assignedEditor?: (number | null) | User;
  /**
   * Estado de la pieza dentro del proceso de redacción. La visibilidad pública se deriva de aquí, no se controla por separado.
   */
  workflow: {
    /**
     * Publicar exige rol autorizado, verificación completa y revisión legal resuelta.
     */
    editorialStatus:
      'draft' | 'editing' | 'fact_check' | 'legal_review' | 'approved' | 'scheduled' | 'published' | 'archived';
    factCheckStatus?: ('not_required' | 'not_started' | 'in_progress' | 'verified' | 'issues_found') | null;
    legalStatus?: ('not_required' | 'pending' | 'approved' | 'changes_required') | null;
    /**
     * Notas internas. Nunca se envían al frontend público (PRD Nº8 §170).
     */
    reviewNotes?: string | null;
  };
  publication?: {
    /**
     * Fecha visible al lector. Debe coincidir con el structured data.
     */
    publishedAt?: string | null;
    /**
     * Se registra una sola vez, en la primera publicación. No se modifica.
     */
    firstPublishedAt?: string | null;
    /**
     * Solo cuando el contenido cambia de forma sustantiva. No se toca por correcciones de forma (PRD SEO §29).
     */
    modifiedAt?: string | null;
    /**
     * Debe ser una fecha futura.
     */
    scheduledAt?: string | null;
  };
  /**
   * Todo es opcional. Si se deja vacío, el sistema deriva los valores del titular, la bajada y la imagen principal.
   */
  seo?: {
    /**
     * Solo si el titular editorial no funciona bien en resultados de búsqueda. No debe cambiar el significado (PRD SEO §27).
     */
    metaTitle?: string | null;
    /**
     * Debe describir, no ser clickbait. Si se deja vacío, se usa la bajada.
     */
    metaDescription?: string | null;
    /**
     * Solo para casos excepcionales. Nunca incluir parámetros de campaña como utm_source (PRD SEO §9).
     */
    canonical?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Excluye esta pieza de los buscadores. Usar con criterio: una nota publicada normalmente debe indexarse.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Reportajes de datos. No se publican sin metodología.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-stories".
 */
export interface DataStory {
  id: number;
  title: string;
  /**
   * Parte final de la URL. Se genera desde el título y se congela al publicar; cambiarlo después crea un redirect automático.
   */
  slug: string;
  /**
   * Se activa en la primera publicación. Protege una URL ya difundida.
   */
  slugLocked?: boolean | null;
  dek?: string | null;
  authors: (number | Author)[];
  /**
   * Ya formateada para lectura, por ejemplo «68.000 M». Opcional.
   */
  headlineFigure?: string | null;
  /**
   * Obligatorio si hay cifra: sin esto la tarjeta la oculta (PRD Nº8 §55).
   */
  headlineFigureContext?: string | null;
  hero?: {
    image?: (number | null) | Media;
    captionOverride?: string | null;
  };
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Procedencia y licencia de cada dataset usado (PRD Nº7 §60).
   */
  datasets?:
    | {
        title: string;
        description?: string | null;
        source: string;
        url?: string | null;
        license?: string | null;
        updatedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Cómo se obtuvieron, limpiaron y analizaron los datos. Obligatoria para publicar.
   */
  methodology?: string | null;
  sources?: (number | Source)[] | null;
  /**
   * Lo registra el sistema. Determina quién puede editar el borrador.
   */
  createdBy?: (number | null) | User;
  /**
   * Quién acompaña esta pieza. Da acceso de edición además del autor.
   */
  assignedEditor?: (number | null) | User;
  /**
   * Estado de la pieza dentro del proceso de redacción. La visibilidad pública se deriva de aquí, no se controla por separado.
   */
  workflow: {
    /**
     * Publicar exige rol autorizado, verificación completa y revisión legal resuelta.
     */
    editorialStatus:
      'draft' | 'editing' | 'fact_check' | 'legal_review' | 'approved' | 'scheduled' | 'published' | 'archived';
    factCheckStatus?: ('not_required' | 'not_started' | 'in_progress' | 'verified' | 'issues_found') | null;
    legalStatus?: ('not_required' | 'pending' | 'approved' | 'changes_required') | null;
    /**
     * Notas internas. Nunca se envían al frontend público (PRD Nº8 §170).
     */
    reviewNotes?: string | null;
  };
  publication?: {
    /**
     * Fecha visible al lector. Debe coincidir con el structured data.
     */
    publishedAt?: string | null;
    /**
     * Se registra una sola vez, en la primera publicación. No se modifica.
     */
    firstPublishedAt?: string | null;
    /**
     * Solo cuando el contenido cambia de forma sustantiva. No se toca por correcciones de forma (PRD SEO §29).
     */
    modifiedAt?: string | null;
    /**
     * Debe ser una fecha futura.
     */
    scheduledAt?: string | null;
  };
  /**
   * Todo es opcional. Si se deja vacío, el sistema deriva los valores del titular, la bajada y la imagen principal.
   */
  seo?: {
    /**
     * Solo si el titular editorial no funciona bien en resultados de búsqueda. No debe cambiar el significado (PRD SEO §27).
     */
    metaTitle?: string | null;
    /**
     * Debe describir, no ser clickbait. Si se deja vacío, se usa la bajada.
     */
    metaDescription?: string | null;
    /**
     * Solo para casos excepcionales. Nunca incluir parámetros de campaña como utm_source (PRD SEO §9).
     */
    canonical?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Excluye esta pieza de los buscadores. Usar con criterio: una nota publicada normalmente debe indexarse.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Piezas de video. Guardar transcripción siempre que exista.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-stories".
 */
export interface VideoStory {
  id: number;
  title: string;
  /**
   * Parte final de la URL. Se genera desde el título y se congela al publicar; cambiarlo después crea un redirect automático.
   */
  slug: string;
  /**
   * Se activa en la primera publicación. Protege una URL ya difundida.
   */
  slugLocked?: boolean | null;
  dek?: string | null;
  authors: (number | Author)[];
  /**
   * El archivo vive en almacenamiento de objetos, no en Payload (PRD Nº10 §77).
   */
  streamUrl?: string | null;
  /**
   * Debe ser nítido: es lo que se ve antes de reproducir (PRD Nº10 §142).
   */
  poster?: (number | null) | Media;
  /**
   * Necesaria para el structured data de VideoObject.
   */
  duration?: number | null;
  /**
   * Accesibilidad, búsqueda interna y SEO. Si la generó una IA, revisarla antes de publicar (PRD Nº10 §87).
   */
  transcript?: string | null;
  relatedArticles?: (number | Article)[] | null;
  /**
   * Lo registra el sistema. Determina quién puede editar el borrador.
   */
  createdBy?: (number | null) | User;
  /**
   * Quién acompaña esta pieza. Da acceso de edición además del autor.
   */
  assignedEditor?: (number | null) | User;
  /**
   * Estado de la pieza dentro del proceso de redacción. La visibilidad pública se deriva de aquí, no se controla por separado.
   */
  workflow: {
    /**
     * Publicar exige rol autorizado, verificación completa y revisión legal resuelta.
     */
    editorialStatus:
      'draft' | 'editing' | 'fact_check' | 'legal_review' | 'approved' | 'scheduled' | 'published' | 'archived';
    factCheckStatus?: ('not_required' | 'not_started' | 'in_progress' | 'verified' | 'issues_found') | null;
    legalStatus?: ('not_required' | 'pending' | 'approved' | 'changes_required') | null;
    /**
     * Notas internas. Nunca se envían al frontend público (PRD Nº8 §170).
     */
    reviewNotes?: string | null;
  };
  publication?: {
    /**
     * Fecha visible al lector. Debe coincidir con el structured data.
     */
    publishedAt?: string | null;
    /**
     * Se registra una sola vez, en la primera publicación. No se modifica.
     */
    firstPublishedAt?: string | null;
    /**
     * Solo cuando el contenido cambia de forma sustantiva. No se toca por correcciones de forma (PRD SEO §29).
     */
    modifiedAt?: string | null;
    /**
     * Debe ser una fecha futura.
     */
    scheduledAt?: string | null;
  };
  /**
   * Todo es opcional. Si se deja vacío, el sistema deriva los valores del titular, la bajada y la imagen principal.
   */
  seo?: {
    /**
     * Solo si el titular editorial no funciona bien en resultados de búsqueda. No debe cambiar el significado (PRD SEO §27).
     */
    metaTitle?: string | null;
    /**
     * Debe describir, no ser clickbait. Si se deja vacío, se usa la bajada.
     */
    metaDescription?: string | null;
    /**
     * Solo para casos excepcionales. Nunca incluir parámetros de campaña como utm_source (PRD SEO §9).
     */
    canonical?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    /**
     * Excluye esta pieza de los buscadores. Usar con criterio: una nota publicada normalmente debe indexarse.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Documentos publicados que respaldan una investigación. Si no puede ser público, no se sube.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence-documents".
 */
export interface EvidenceDocument {
  id: number;
  title: string;
  /**
   * Por qué este documento importa. Un documento sin contexto es un archivo.
   */
  description?: string | null;
  /**
   * Contrato, acta, resolución, oficio…
   */
  documentType?: string | null;
  institution?: string | null;
  /**
   * La fecha del documento, no la de su carga.
   */
  documentDate?: string | null;
  pageCount?: number | null;
  relatedInvestigation?: (number | null) | Investigation;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Redirecciones permanentes. Se evalúan antes de devolver un 404.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Ruta anterior, con barra inicial. Ejemplo: /articulo/titulo-viejo
   */
  from: string;
  /**
   * Ruta destino. Debe existir, o se encadena un redirect hacia un 404.
   */
  to: string;
  /**
   * Para cambios editoriales permanentes usar 301 o 308 (PRD SEO §16). Los temporales no transfieren autoridad.
   */
  statusCode: '301' | '308' | '302' | '307';
  /**
   * Por qué existe. Sin esto, nadie sabrá si se puede retirar.
   */
  reason?: string | null;
  active?: boolean | null;
  /**
   * Marca las que generó el sistema al cambiar un slug publicado.
   */
  automatic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Correcciones públicas. No modifican el texto original: se muestran junto a él.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corrections".
 */
export interface Correction {
  id: number;
  /**
   * La pieza a la que corresponde. Se muestra dentro de ella.
   */
  about:
    | {
        relationTo: 'articles';
        value: number | Article;
      }
    | {
        relationTo: 'investigations';
        value: number | Investigation;
      }
    | {
        relationTo: 'opinions';
        value: number | Opinion;
      }
    | {
        relationTo: 'data-stories';
        value: number | DataStory;
      }
    | {
        relationTo: 'video-stories';
        value: number | VideoStory;
      };
  type: 'correction' | 'clarification' | 'update' | 'editor_note';
  /**
   * Qué decía antes, qué dice ahora y por qué cambió. Concreto: «Se corrigió la cifra de 3.200 a 3.020 millones», no «se corrigieron errores».
   */
  summary: string;
  /**
   * Cuándo se emitió. El lector necesita saber si es anterior a cuando leyó.
   */
  issuedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registro append-only. No se puede editar ni borrar, tampoco por un administrador.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: number;
  timestamp: string;
  action:
    | 'login_success'
    | 'login_failure'
    | 'user_created'
    | 'user_disabled'
    | 'role_changed'
    | 'content_published'
    | 'content_unpublished'
    | 'content_deleted'
    | 'settings_changed';
  /**
   * Identificador del usuario. Vacío cuando la acción fue anónima.
   */
  actorId?: string | null;
  /**
   * El rol en el momento del hecho. Se guarda literal y no por relación: si después cambia, el registro debe seguir diciendo qué autoridad se ejerció entonces.
   */
  actorRole?: string | null;
  resourceType?: string | null;
  resourceId?: string | null;
  /**
   * PRD Nº5 §115: un intento denegado también se registra. Los accesos rechazados son la señal temprana.
   */
  result: 'allowed' | 'denied';
  /**
   * Correlaciona el evento con los logs técnicos (PRD Nº4 §83).
   */
  requestId?: string | null;
  /**
   * Contexto adicional. NUNCA secretos, tokens, URLs presignadas ni contenido de documentos (PRD Nº5 §55).
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Denuncias recibidas. Ninguna se convierte en contenido automáticamente.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tips".
 */
export interface Tip {
  id: number;
  title: string;
  description: string;
  location?: string | null;
  /**
   * Si está marcada, no se guardó ningún dato de contacto.
   */
  anonymous?: boolean | null;
  contactName?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  attachments?:
    | {
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Derivar NO publica nada: solo marca que la redacción decidió trabajarla.
   */
  status: 'new' | 'reviewing' | 'archived' | 'escalated';
  /**
   * Nunca se muestran públicamente.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'syncSearch';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'syncSearch') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'topics';
        value: number | Topic;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'investigations';
        value: number | Investigation;
      } | null)
    | ({
        relationTo: 'opinions';
        value: number | Opinion;
      } | null)
    | ({
        relationTo: 'data-stories';
        value: number | DataStory;
      } | null)
    | ({
        relationTo: 'video-stories';
        value: number | VideoStory;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'evidence-documents';
        value: number | EvidenceDocument;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'corrections';
        value: number | Correction;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: number | AuditEvent;
      } | null)
    | ({
        relationTo: 'tips';
        value: number | Tip;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  status?: T;
  department?: T;
  mfaEnabled?: T;
  lastLoginAt?: T;
  passwordChangedAt?: T;
  securityNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  slugLocked?: T;
  jobTitle?: T;
  shortBio?: T;
  bio?: T;
  expertise?:
    | T
    | {
        area?: T;
        id?: T;
      };
  emailPublic?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  active?: T;
  portrait?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonical?: T;
        ogTitle?: T;
        ogDescription?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  slugLocked?: T;
  description?: T;
  parent?: T;
  navigationLabel?: T;
  order?: T;
  active?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonical?: T;
        ogTitle?: T;
        ogDescription?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  slugLocked?: T;
  description?: T;
  relatedTopics?: T;
  image?: T;
  active?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonical?: T;
        ogTitle?: T;
        ogDescription?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  slugLocked?: T;
  roleDescription?: T;
  organizations?: T;
  description?: T;
  portrait?: T;
  publicSources?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  slugLocked?: T;
  organizationType?: T;
  logo?: T;
  description?: T;
  website?: T;
  location?: T;
  publicSources?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  checksum?: T;
  alt?: T;
  decorative?: T;
  caption?: T;
  credit?: T;
  photographer?: T;
  source?: T;
  mediaType?: T;
  license?: T;
  copyrightHolder?: T;
  rightsExpiration?: T;
  syntheticMedia?: T;
  usageNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        article?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        portrait?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLocked?: T;
  dek?: T;
  contentType?: T;
  category?: T;
  topics?: T;
  authors?: T;
  hero?:
    | T
    | {
        image?: T;
        captionOverride?: T;
      };
  body?: T;
  relations?:
    | T
    | {
        relatedArticles?: T;
        people?: T;
        organizations?: T;
        sources?: T;
      };
  createdBy?: T;
  assignedEditor?: T;
  workflow?:
    | T
    | {
        editorialStatus?: T;
        factCheckStatus?: T;
        legalStatus?: T;
        reviewNotes?: T;
      };
  publication?:
    | T
    | {
        publishedAt?: T;
        firstPublishedAt?: T;
        modifiedAt?: T;
        scheduledAt?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonical?: T;
        ogTitle?: T;
        ogDescription?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investigations_select".
 */
export interface InvestigationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLocked?: T;
  dek?: T;
  hero?:
    | T
    | {
        image?: T;
        captionOverride?: T;
      };
  authors?: T;
  editors?: T;
  summary?: T;
  keyFindings?:
    | T
    | {
        headline?: T;
        description?: T;
        sources?: T;
        importance?: T;
        id?: T;
      };
  chapters?:
    | T
    | {
        title?: T;
        slug?: T;
        intro?: T;
        body?: T;
        sources?: T;
        id?: T;
      };
  timeline?:
    | T
    | {
        date?: T;
        title?: T;
        description?: T;
        sources?: T;
        id?: T;
      };
  topics?: T;
  people?: T;
  organizations?: T;
  sources?: T;
  methodology?: T;
  updates?:
    | T
    | {
        date?: T;
        summary?: T;
        id?: T;
      };
  createdBy?: T;
  assignedEditor?: T;
  workflow?:
    | T
    | {
        editorialStatus?: T;
        factCheckStatus?: T;
        legalStatus?: T;
        reviewNotes?: T;
      };
  publication?:
    | T
    | {
        publishedAt?: T;
        firstPublishedAt?: T;
        modifiedAt?: T;
        scheduledAt?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonical?: T;
        ogTitle?: T;
        ogDescription?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opinions_select".
 */
export interface OpinionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLocked?: T;
  dek?: T;
  contentNature?: T;
  author?: T;
  hero?:
    | T
    | {
        image?: T;
        captionOverride?: T;
      };
  body?: T;
  createdBy?: T;
  assignedEditor?: T;
  workflow?:
    | T
    | {
        editorialStatus?: T;
        factCheckStatus?: T;
        legalStatus?: T;
        reviewNotes?: T;
      };
  publication?:
    | T
    | {
        publishedAt?: T;
        firstPublishedAt?: T;
        modifiedAt?: T;
        scheduledAt?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonical?: T;
        ogTitle?: T;
        ogDescription?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-stories_select".
 */
export interface DataStoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLocked?: T;
  dek?: T;
  authors?: T;
  headlineFigure?: T;
  headlineFigureContext?: T;
  hero?:
    | T
    | {
        image?: T;
        captionOverride?: T;
      };
  body?: T;
  datasets?:
    | T
    | {
        title?: T;
        description?: T;
        source?: T;
        url?: T;
        license?: T;
        updatedAt?: T;
        id?: T;
      };
  methodology?: T;
  sources?: T;
  createdBy?: T;
  assignedEditor?: T;
  workflow?:
    | T
    | {
        editorialStatus?: T;
        factCheckStatus?: T;
        legalStatus?: T;
        reviewNotes?: T;
      };
  publication?:
    | T
    | {
        publishedAt?: T;
        firstPublishedAt?: T;
        modifiedAt?: T;
        scheduledAt?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonical?: T;
        ogTitle?: T;
        ogDescription?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-stories_select".
 */
export interface VideoStoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLocked?: T;
  dek?: T;
  authors?: T;
  streamUrl?: T;
  poster?: T;
  duration?: T;
  transcript?: T;
  relatedArticles?: T;
  createdBy?: T;
  assignedEditor?: T;
  workflow?:
    | T
    | {
        editorialStatus?: T;
        factCheckStatus?: T;
        legalStatus?: T;
        reviewNotes?: T;
      };
  publication?:
    | T
    | {
        publishedAt?: T;
        firstPublishedAt?: T;
        modifiedAt?: T;
        scheduledAt?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonical?: T;
        ogTitle?: T;
        ogDescription?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  title?: T;
  sourceType?: T;
  visibility?: T;
  publisher?: T;
  url?: T;
  archiveUrl?: T;
  publishedAt?: T;
  accessedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence-documents_select".
 */
export interface EvidenceDocumentsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  documentType?: T;
  institution?: T;
  documentDate?: T;
  pageCount?: T;
  relatedInvestigation?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  statusCode?: T;
  reason?: T;
  active?: T;
  automatic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corrections_select".
 */
export interface CorrectionsSelect<T extends boolean = true> {
  about?: T;
  type?: T;
  summary?: T;
  issuedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  timestamp?: T;
  action?: T;
  actorId?: T;
  actorRole?: T;
  resourceType?: T;
  resourceId?: T;
  result?: T;
  requestId?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tips_select".
 */
export interface TipsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  location?: T;
  anonymous?: T;
  contactName?: T;
  contactEmail?: T;
  contactPhone?: T;
  attachments?:
    | T
    | {
        file?: T;
        id?: T;
      };
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Identidad del sitio y datos del publisher para structured data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteDescription?: string | null;
  /**
   * PRD SEO §67: datos reales y visibles. Un medio sin contacto parece una entidad anónima.
   */
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  /**
   * Alimenta el Organization de schema.org. PRD SEO §37: logo oficial, URL permanente, sin mockups.
   */
  organization?: {
    legalName?: string | null;
    logo?: (number | null) | Media;
    /**
     * Solo perfiles verificables (PRD SEO §35).
     */
    sameAs?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Menús del sitio. Nunca se codifican en componentes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * PRD Nº8 §11: sin mega-menú. Si no cabe en una línea, la jerarquía editorial está mal.
   */
  primary?:
    | {
        label: string;
        linkType?: ('internal' | 'external') | null;
        /**
         * La URL se deriva del slug, así el enlace sobrevive a un cambio de slug.
         */
        category?: (number | null) | Category;
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  secondary?:
    | {
        label: string;
        linkType?: ('internal' | 'external') | null;
        /**
         * La URL se deriva del slug, así el enlace sobrevive a un cambio de slug.
         */
        category?: (number | null) | Category;
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footer?:
    | {
        title: string;
        links?:
          | {
              label: string;
              linkType?: ('internal' | 'external') | null;
              /**
               * La URL se deriva del slug, así el enlace sobrevive a un cambio de slug.
               */
              category?: (number | null) | Category;
              url?: string | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  social?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Orden de la portada. Se reordena arrastrando, sin tocar código.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  bands?:
    | (
        | {
            /**
             * PRD Nº8 §38: el hero admite nota, investigación o dato. Vacío = la publicación más reciente.
             */
            article?:
              | ({
                  relationTo: 'articles';
                  value: number | Article;
                } | null)
              | ({
                  relationTo: 'investigations';
                  value: number | Investigation;
                } | null)
              | ({
                  relationTo: 'data-stories';
                  value: number | DataStory;
                } | null);
            /**
             * PRD Nº8 §39: 7 columnas de imagen y 5 de texto, o al revés.
             */
            imageFirst?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Lo que se imprime en el SectionHeader. Vacío = sin encabezado.
             */
            title?: string | null;
            limit?: number | null;
            /**
             * Opcional. Vacío = todas las secciones.
             */
            category?: (number | null) | Category;
            /**
             * PRD Nº8 §44: no todas con el mismo peso.
             */
            leadCount?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'secondary';
          }
        | {
            /**
             * Lo que se imprime en el SectionHeader. Vacío = sin encabezado.
             */
            title?: string | null;
            limit?: number | null;
            /**
             * Opcional. Vacío = todas las secciones.
             */
            category?: (number | null) | Category;
            id?: string | null;
            blockName?: string | null;
            blockType: 'latest';
          }
        | {
            investigationsTitle?: string | null;
            analysisTitle?: string | null;
            dataTitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'trio';
          }
        | {
            /**
             * Lo que se imprime en el SectionHeader. Vacío = sin encabezado.
             */
            title?: string | null;
            limit?: number | null;
            /**
             * Opcional. Vacío = todas las secciones.
             */
            category?: (number | null) | Category;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'investigations';
          }
        | {
            /**
             * Lo que se imprime en el SectionHeader. Vacío = sin encabezado.
             */
            title?: string | null;
            limit?: number | null;
            /**
             * Opcional. Vacío = todas las secciones.
             */
            category?: (number | null) | Category;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'analysis';
          }
        | {
            /**
             * Lo que se imprime en el SectionHeader. Vacío = sin encabezado.
             */
            title?: string | null;
            limit?: number | null;
            /**
             * Opcional. Vacío = todas las secciones.
             */
            category?: (number | null) | Category;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'data';
          }
        | {
            /**
             * Lo que se imprime en el SectionHeader. Vacío = sin encabezado.
             */
            title?: string | null;
            limit?: number | null;
            /**
             * Opcional. Vacío = todas las secciones.
             */
            category?: (number | null) | Category;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            /**
             * Lo que se imprime en el SectionHeader. Vacío = sin encabezado.
             */
            title?: string | null;
            limit?: number | null;
            /**
             * Opcional. Vacío = todas las secciones.
             */
            category?: (number | null) | Category;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'opinion';
          }
        | {
            title?: string | null;
            description?: string | null;
            ctaLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Barra de última hora. Siempre con fecha de expiración.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breaking-news".
 */
export interface BreakingNew {
  id: number;
  enabled?: boolean | null;
  /**
   * Determina el color de la barra. El texto siempre acompaña al color: nunca se comunica solo con color.
   */
  severity: 'breaking' | 'alert' | 'developing' | 'confirmed';
  headline: string;
  description?: string | null;
  relatedArticle?: (number | null) | Article;
  startsAt: string;
  /**
   * Obligatoria: evita banners olvidados (PRD Nº5 §26).
   */
  expiresAt: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  organization?:
    | T
    | {
        legalName?: T;
        logo?: T;
        sameAs?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  primary?:
    | T
    | {
        label?: T;
        linkType?: T;
        category?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  secondary?:
    | T
    | {
        label?: T;
        linkType?: T;
        category?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              linkType?: T;
              category?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  bands?:
    | T
    | {
        hero?:
          | T
          | {
              article?: T;
              imageFirst?: T;
              id?: T;
              blockName?: T;
            };
        secondary?:
          | T
          | {
              title?: T;
              limit?: T;
              category?: T;
              leadCount?: T;
              id?: T;
              blockName?: T;
            };
        latest?:
          | T
          | {
              title?: T;
              limit?: T;
              category?: T;
              id?: T;
              blockName?: T;
            };
        trio?:
          | T
          | {
              investigationsTitle?: T;
              analysisTitle?: T;
              dataTitle?: T;
              id?: T;
              blockName?: T;
            };
        investigations?:
          | T
          | {
              title?: T;
              limit?: T;
              category?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        analysis?:
          | T
          | {
              title?: T;
              limit?: T;
              category?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        data?:
          | T
          | {
              title?: T;
              limit?: T;
              category?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              title?: T;
              limit?: T;
              category?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        opinion?:
          | T
          | {
              title?: T;
              limit?: T;
              category?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              title?: T;
              description?: T;
              ctaLabel?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breaking-news_select".
 */
export interface BreakingNewsSelect<T extends boolean = true> {
  enabled?: T;
  severity?: T;
  headline?: T;
  description?: T;
  relatedArticle?: T;
  startsAt?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncSearch".
 */
export interface TaskSyncSearch {
  input: {
    collection: string;
    documentId: string;
    operation: 'upsert' | 'delete';
    version: string;
  };
  output: {
    result?: ('upserted' | 'deleted' | 'superseded' | 'not-configured') | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}